(function(){'use strict';
let currentMode='A',lastResult=null,bulkRows=[];const $=id=>document.getElementById(id);
function activateTab(name){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));$('tab-'+name).classList.add('active');if(name==='history')renderHistory();}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>activateTab(tab.dataset.tab)));
$('gotoFormulas').addEventListener('click',e=>{e.preventDefault();activateTab('formulas')});
$('themeToggle').addEventListener('click',()=>{const b=document.body,d=b.getAttribute('data-theme')==='dark';b.setAttribute('data-theme',d?'light':'dark');$('themeToggle').textContent=d?'🌙':'☀️'});
function setMode(m){currentMode=m;$('modeA').classList.toggle('active',m==='A');$('modeB').classList.toggle('active',m==='B');document.querySelectorAll('[data-only]').forEach(el=>el.classList.toggle('hidden',el.dataset.only!==m));clearResult();calculate();}
$('modeA').addEventListener('click',()=>setMode('A'));$('modeB').addEventListener('click',()=>setMode('B'));
['length','lengthUnit','gravelAmount','gravelUnit','width','widthUnit','thickness','thicknessUnit','density','densityUnit','wastePct','resultUnit','lengthUnitOut'].forEach(id=>{const el=$(id);if(el)el.addEventListener('input',calculate)});$('calcBtn').addEventListener('click',calculate);
function val(id){return $(id).value}function clearResult(){lastResult=null;$('resultBig').textContent='—';$('resultSub').textContent='';$('breakdown').innerHTML='<li>Enter values and press Calculate.</li>';$('saveBtn').disabled=true;}function showErrors(errors){$('errors').innerHTML=errors.length?'<ul>'+errors.map(e=>`<li>${e}</li>`).join('')+'</ul>':''}function renderBreakdown(lines){$('breakdown').innerHTML=lines.map(l=>`<li>${l}</li>`).join('')}
function calculate(){const density=val('density'),densityUnit=val('densityUnit'),width=val('width'),widthUnit=val('widthUnit'),thickness=val('thickness'),thicknessUnit=val('thicknessUnit'),wastePct=val('wastePct');let errors=[];if(currentMode==='A'){const length=val('length'),lengthUnit=val('lengthUnit'),resultUnit=val('resultUnit');errors=GravelCalc.validateNumbers({'Length':length,'Width':width,'Thickness':thickness,'Density':density,'Waste %':wastePct});if(errors.length){showErrors(errors);clearResult();return}showErrors([]);const out=GravelCalc.calcGravelNeeded({length,lengthUnit,width,widthUnit,thickness,thicknessUnit,density,densityUnit,wastePct,resultUnit});const unitLabel=resultUnit==='t'?'tonnes':'kg';$('resultBig').textContent=`${out.result} ${unitLabel}`;$('resultSub').textContent=`Volume needed: ${out.volumeM3} m³`;renderBreakdown(out.breakdown);lastResult={mode:'A — Gravel needed',datetime:new Date().toLocaleString(),inputs:{length:`${length} ${lengthUnit}`,width:`${width} ${widthUnit}`,thickness,thicknessUnit,density:`${density} ${densityUnit==='tm3'?'t/m3':'kg/m3'}`,wastePct},result:out.result,resultUnit:unitLabel};}else{const gravelAmount=val('gravelAmount'),gravelUnit=val('gravelUnit'),lengthUnit=val('lengthUnitOut');errors=GravelCalc.validateNumbers({'Gravel available':gravelAmount,'Width':width,'Thickness':thickness,'Density':density,'Waste %':wastePct});if(errors.length){showErrors(errors);clearResult();return}showErrors([]);const out=GravelCalc.calcDistanceCovered({gravelAmount,gravelUnit,width,widthUnit,thickness,thicknessUnit,density,densityUnit,wastePct,lengthUnit});$('resultBig').textContent=`${out.lengthOut} ${out.lengthUnit}`;$('resultSub').textContent=`Road length covered (${out.volumeM3} m³ spread)`;renderBreakdown(out.breakdown);lastResult={mode:'B — Distance covered',datetime:new Date().toLocaleString(),inputs:{length:'',gravelAmount:`${gravelAmount} ${gravelUnit}`,width:`${width} ${widthUnit}`,thickness,thicknessUnit,density:`${density} ${densityUnit==='tm3'?'t/m3':'kg/m3'}`,wastePct},result:out.lengthOut,resultUnit:out.lengthUnit};}$('saveBtn').disabled=false;}
$('saveBtn').addEventListener('click',async()=>{if(!lastResult)return;await window.api.addHistory(lastResult);$('saveBtn').disabled=true;flash('exportMsg','Saved to history.')});
async function renderHistory(){const list=await window.api.getHistory();const body=$('historyBody');if(!list.length){body.innerHTML='<tr><td colspan="10" class="empty">No saved calculations yet.</td></tr>';return}body.innerHTML=list.map(r=>`<tr><td>${r.datetime}</td><td>${r.mode}</td><td>${r.inputs.length||r.inputs.gravelAmount||''}</td><td>${r.inputs.width||''}</td><td>${r.inputs.thickness??''} ${r.inputs.thicknessUnit??''}</td><td>${r.inputs.density||''}</td><td>${r.inputs.wastePct??0}</td><td><strong>${r.result}</strong></td><td>${r.resultUnit}</td><td><button class="row-del" data-id="${r.id}">✕</button></td></tr>`).join('');body.querySelectorAll('.row-del').forEach(btn=>btn.addEventListener('click',async()=>{await window.api.deleteHistory(Number(btn.dataset.id));renderHistory()}));}
$('clearHistory').addEventListener('click',async()=>{await window.api.clearHistory();renderHistory();flash('exportMsg','History cleared.')});$('exportXlsx').addEventListener('click',async()=>flash('exportMsg',(await window.api.exportXlsx()).message));
$('copyFormulas').addEventListener('click',async()=>{const text='Volume (m3) = Length x Width x Thickness\nWeight (kg) = Volume x Density\nMode A total = base x (1 + Waste%/100)\nMode B length = (available kg / (1 + Waste%/100) / density) / (width x thickness)';try{await navigator.clipboard.writeText(text);flash('copyMsg','Copied to clipboard ✓')}catch{flash('copyMsg','Copy failed')}});
$('downloadTemplate').addEventListener('click',async()=>flash('bulkMsg',(await window.api.downloadBulkTemplate()).message));
$('uploadBulk').addEventListener('click',async()=>{const res=await window.api.importBulk();if(!res.ok){flash('bulkMsg',res.message);return}bulkRows=res.rows||[];renderBulk(bulkRows,res.summary);flash('bulkMsg',`Imported ${res.summary.totalRows} row(s) from ${res.filePath}`)});
$('exportBulkXlsx').addEventListener('click',async()=>flash('bulkMsg',(await window.api.exportBulkXlsx(bulkRows)).message));$('exportBulkCsv').addEventListener('click',async()=>flash('bulkMsg',(await window.api.exportBulkCsv(bulkRows)).message));$('addBulkHistory').addEventListener('click',async()=>{let count=0;for(const r of bulkRows.filter(r=>r.ok&&r.historyRecord)){await window.api.addHistory(r.historyRecord);count++}flash('bulkMsg',`Added ${count} valid result(s) to History.`)});
function renderBulk(rows,summary){$('sumTotal').textContent=summary.totalRows;$('sumOk').textContent=summary.succeeded;$('sumFail').textContent=summary.failed;$('sumTonnes').textContent=`${summary.totalModeATonnes} t`;$('exportBulkXlsx').disabled=$('exportBulkCsv').disabled=!rows.length;$('addBulkHistory').disabled=!rows.some(r=>r.ok);const body=$('bulkBody');if(!rows.length){body.innerHTML='<tr><td colspan="11" class="empty">Upload a bulk Excel file to calculate results.</td></tr>';return}body.innerHTML=rows.map(r=>`<tr class="${r.ok?'bulk-ok':'bulk-error'}"><td>${r.rowNumber}</td><td>${r.mode||''}</td><td>${r.mode==='A'?(r.length||''):(r.gravelAmount||'')}</td><td>${r.width||''} ${r.widthUnit||''}</td><td>${r.thickness||''} ${r.thicknessUnit||''}</td><td>${r.density||''} ${r.densityUnit||''}</td><td>${r.wastePct??0}</td><td>${r.volumeM3||''}</td><td><strong>${r.result||''}</strong></td><td>${r.resultUnit||''}</td><td>${r.status}</td></tr>`).join('')}
function flash(id,msg){const el=$(id);if(el){el.textContent=msg;setTimeout(()=>{if(el.textContent===msg)el.textContent=''},6000)}}
setMode('A');
})();
